name: Project CI/CD

on:
  push:
    paths:
      - 'master.py'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'master.py'
      - 'requirements.txt'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check file syntax
      run: |
        python -m py_compile master.py

    - name: Run on input video
      run: |
        python master.py -p test-assets/sample.mp4 -f 2 V
  
    - name: Upload output video
      uses: actions/upload-artifact@v3
      with:
        name: inference-output
        path: output.mp4
